server:
  port: 8204 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  rabbitmq:
    host: 111.91.237.21
    port: 5673
    username: guest
    password: guest
tencent:
  sms:
    secretId: 111
    secretKey: 111
    sdkAppId: 111
    templateId: 11
    signName: 11
